### ISSUE TITLE
I can't make the size work

### ISSUE THREAD

**Issue by ghost** [tienpham94/react-awesome-spinners#18]
Hi,
thank you for this component
I can't make the size smaller. I'm using it like this

```
import { Spinner } from 'react-awesome-spinners'
<Spinner color="#be97e8" size={64} sizeUnit='px' />
```
whether I do 32 or 16 it's always the same(64) size. Tried "32px" and "32" as well. Is there anything wrong on how I'm using it?

**Comment by noedsondutra** [comment]
Hey, I couldn't make my spinner work with size too.

But, I've found the solution, this package:
https://github.com/JoshK2/react-spinners-css

_Look at the table an notice that some spinners can't be sized_

I hope have helped!

**Comment by ruthcmoratagil** [comment]
Hi,

I have the same issue as @canercak:

```
import { Spinner } from 'react-awesome-spinners';
<Spinner color='#2B71E4' size={12} />
```

Color works. Size does not. Could you please let us know if that is the right way to do it?

**Comment by noedsondutra** [comment]
Hi achtur,

Some spinners can't be sized.
Look at the link I sent in the message above yours.

On the link, there is a table with a column "size: number", "-" means the spinner can't be sized.

Hope have helped.

**Comment by ruthcmoratagil** [comment]
Thanks @noedsondutra! It did help.
I guess I will need to look for a different package if I want to use a sizable spinner...
