### ISSUE TITLE
Small motion optimization suggestion

### ISSUE THREAD

**Issue by maxsbelt** [tienpham94/react-awesome-spinners#3]
Thanks for good project! I was surfing through the code and noticed that `keyframes` calls in all components are wrapped with additional function that actually isn't necessary. I think such modification can increase performance a little bit. WDYT?

<img width="547" alt="Screenshot 2019-07-07 at 20 58 20" src="https://user-images.githubusercontent.com/950216/60772109-34d2a900-a0fa-11e9-87c3-39dd9ba30147.png">

**Comment by tienpham94** [comment]
Hi @maxsbelt thank you for checking out the project! Yeah the props passing was initially done because I wanted to make it customizable, but its not anymore needed. I will improve that in the next release, thank you for commenting!
