### ISSUE TITLE
[suggestion] Heart spinner shape improvement

### ISSUE THREAD

**Issue by gratiaa** [tienpham94/react-awesome-spinners#4]
Hi, @tienpham94 ! I like your awesome spinners :) 
I looked through all of them and found a heart one has a little room for improvement.
Can I open a PR suggesting a polished version of heart spinner?

## before
![heart_before](https://user-images.githubusercontent.com/17661000/60975163-75cef580-a366-11e9-9cc0-16d3cddbec43.gif)

## after
![heart_after](https://user-images.githubusercontent.com/17661000/60975180-7bc4d680-a366-11e9-9cad-30a63f98c4aa.gif)

**Comment by tienpham94** [comment]
Hi @gratiaa, thank you for asking! Yes please go ahead, that would be super awesome!
